version: '3.9'
services:

   rmbscd:
      tty: true
      build:
         context: .
         shm_size: '12gb'
      shm_size: '12gb'
      ports:
         - '4000:4000'
         - '8888:8888' #Notebook port
         - '6006:6006' # Tensorboard

      container_name: 'rmbscd'
      volumes:
         - ./:/appli

      networks:
         - rmbscd_network
      # deploy:
      #    resources:
      #       reservations:
      #          devices:
      #             - capabilities: [gpu]
      #               driver: nvidia

networks:
   rmbscd_network:
